# Generated by Django 5.2.8 on 2026-03-30 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methodology', '0005_artifact_artifactinput_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Short descriptive title for the skill', max_length=200)),
                ('content', models.TextField(blank=True, default='', help_text='Markdown content: steps, best practices, examples, prerequisites, tools, references')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.OneToOneField(help_text='Parent activity for this skill (1:1 relationship)', on_delete=django.db.models.deletion.CASCADE, related_name='skill', to='methodology.activity')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['title'],
            },
        ),
    ]
