# Generated by Django 6.0.3 on 2026-03-31 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("methodology", "0007_agent"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="agent",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional AI agent assigned to perform this activity",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="activities",
                to="methodology.agent",
            ),
        ),
    ]
