# Generated by Django 6.0.5 on 2026-06-22 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methodology', '0023_pipchange_phase_and_structural_refs'),
    ]

    operations = [
        migrations.AddField(
            model_name='processimprovementproposal',
            name='galdr_holistic_assessment',
            field=models.TextField(blank=True, default='', help_text='Galdr v2 overall coherence reasoning (when GALDR_USE_TARGET_STATE is enabled).'),
        ),
    ]
