# Generated by Django 6.0 on 2026-07-17 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methodology', '0024_pip_galdr_holistic_assessment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='type',
            field=models.CharField(choices=[('Document', 'Document'), ('Template', 'Template'), ('Code', 'Code'), ('Diagram', 'Diagram'), ('Data', 'Data'), ('Reference Architecture', 'Reference Architecture'), ('Other', 'Other')], default='Document', help_text="Artifact type. Example: 'Document'", max_length=50),
        ),
    ]
